name: Generate QMKPID

on:
  pull_request:
    types:
      - closed

jobs:
  generate_pid:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1
    
    - name: Get list of files
      if: github.event.pull_request.merged
      run: |
        FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
        echo $FILES