name: Generate QMKPID

on:
  pull_request:
    types:
      - closed

jobs:
  generate_pid:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1
    
    - name: Get list of files
      if: github.event.pull_request.merged
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES