name: Generate QMKPID

on:
  pull_request:
    types:
      - closed

jobs:
  generate_pid:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1
    
    - name: Get keyboard config
      if: github.event.pull_request.merged
      run: |
        CONFIG=$(git diff-tree --no-commit-id -m --name-only -r ${{ github.sha }}) | grep config.h | grep -v keymaps
        echo "::set-env name=keyboard_config::$CONFIG"
        echo "::set-env name=pids_json::.github/workflows/qmkpid/pids.json"

    - name: Generate PID
      run: .github/workflows/qmkpid/pid.py

