name: Generate QMKPID

on:
  pull_request:
    types:
      - closed

jobs:
  generate_pid:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1
    
    - name: Get keyboard config
      if: github.event.pull_request.merged
      run: |
        export PIDS_JSON_PATH=".github/workflows/qmkpid/pids.json"
        export KEYBOARD_CONFIG_PATH=$(git diff-tree --no-commit-id -m --name-only -r ${{ github.sha }} | grep config.h | grep -v keymaps) && python3 .github/workflows/qmkpid/pid.py || echo "No keyboards added"

    - name: Generate PID
      run: echo "todo, break the stuff into these steps"

    - name: Commit tag generated PID to master
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Generated QMKPID" -a
        git tag -a BOT:PID -m "Assigned PID for keyboard"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

