name: Generate QMKPID

on:
  pull_request:
    types:
      - closed

jobs:
  generate_pid:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1
    
    - name: Get keyboard config
      if: github.event.pull_request.merged
      id: get_config
      run: |
        echo "##[set-output name=config;]$(git diff-tree --no-commit-id -m --name-only -r ${{ github.sha }} | grep config.h | grep -v keymaps || echo 'No keyboards added')"

    - name: Generate QMKPID
      if: steps.get_config.outputs.config != 'No keyboards added'
      id: generate_qmkpid
      run: |
        export KEYBOARD_CONFIG_PATH=${{ steps.get_config.outputs.config }}
        export PIDS_JSON_PATH=".github/workflows/qmkpid/pids.json"
        OUTPUT=$(python3 .github/workflows/qmkpid/pid.py)
        echo $OUTPUT
        echo "##[set-output name=output;]"$OUTPUT
        echo "##[set-output name=pid;]"$(echo $OUTPUT | tr -d '[:space:]' | tail -c 4)

    - name: Commit tag generated PID to master
      run: |
        echo "O:"${{ steps.generate_qmkpid.output }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Generated QMKPID"
        git tag -a BOTPID_0x${{ steps.generate_qmkpid.pid }} -m "Assigned QMKPID 0x${{ steps.generate_qmkpid.pid }} for keyboard"

    - name: Push changes
      if: 1 == 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

